 const ActionTypes = {
    STUDENT:'STUDENT',
    COMPANY : 'COMPANY',
    ADMIN : 'ADMIN',
    MYALLPOSTS : 'MYALLPOSTS',
    ALLSTUDENTS : 'ALLSTUDENTS',
    ALLJOBS : 'ALLJOBS',
    ALLUSERS : 'ALLUSERS',
    USERDELETE : 'USERDELETE',
    STUDENTDELETE : 'STUDENTDELETE',
    COMPANYDELETE : 'COMPANYDELETE',
    ERRORMSG : 'ERRORMSG'

   
}

export default ActionTypes;
